### ISSUE TITLE
There're not possible to add new portHuTV integration

### ISSUE THREAD

**Issue by kovaccs** [vorostamas/portHuTV-homeassistant#17]
## Version of the custom_component
Home Assistant OS 6.1
core-2021.7.4
supervisor-2021.06.8

## Describe the bug
On Integration page -> add new integration -> look for Port.hu TV --- that's Ok!
Adding Channel-id, all requests will be rejected: "The Channel ID is wrong".
(Cannel-id from "channel_mapping.json" file of course.)
The previously created integrations work properly (all TV sensors).

Kovaccsaba

**Comment by KixMan28** [comment]
@vorostamas Van valami fejlemény ezzel a problémával kapcsolatban? Én sem tudok hozzáadni új csatornát az integrációhoz.

**Comment by kovaccs** [comment]
> @vorostamas Van valami fejlemény ezzel a problémával kapcsolatban? Én sem tudok hozzáadni új csatornát az integrációhoz.

Ott van a fix feletted. Javítsd a saját tárolt fáljaid két helyen.

**Comment by KixMan28** [comment]
> > @vorostamas Van valami fejlemény ezzel a problémával kapcsolatban? Én sem tudok hozzáadni új csatornát az integrációhoz.
> 
> Ott van a fix feletted. Javítsd a saját tárolt fáljaid két helyen.

Köszi a válaszodat. Nem erősségem a Github, ezért nem tudom értelmezni a pull request, branch, fork, stb kulcsszavakat. 
Másfelől ha ez egy ismert probléma és van rá megoldás, akkor miért nincs kint az 1.0.7-es verzió frissítésként a HACS-ban?

**Comment by kovaccs** [comment]
Mert tamás nem tette ki. Ha gondolod tételesen leírom mit kell javítanod.

Üdvözlettel:
Kovaccsaba

--
Kovács Csaba István
nyug. főiskolai docens - IT rendszermérnök, Dunaújvárosi Egyetem, +36 30
6385050
Elnökségi tag - HUNGARNET Egyesület -
http://www.hungarnet.hu/hu/kovacs_csaba_istvan


KixMan28 ***@***.***> ezt írta (időpont: 2021. szept. 22.,
Sze, 11:39):

**Comment by KixMan28** [comment]
@kovaccs Köszi az ajánlatodat. Megoldottam. Bemásoltam a zöld sorokat a két kérdéses fájlba és működik.
