### ISSUE TITLE
Entitás attribútumok

### ISSUE THREAD

**Issue by sonycim** [vorostamas/portHuTV-homeassistant#20]
Üdvözletem!

A napokban telepítettem ezt a remekbe szabott kiegészítőt; Home Assistant alatt, HACS.-ban.
Home Assistent verzió: 2022.6.5
Kieg. verzió: v1.0.7

Az éppen futó műsort remekül jelzi.
Azonban az entitásokhoz tartozó attribútumok hiányoznak.
Feltételezem a HA verzió váltások okozta változások okozhatják a problémát.
Remélem van mód az integráció frissítésére, hogy a műsorújság is használhatóvá váljon.

Előre is köszönöm!

/Boros László

**Comment by vorostamas** [comment]
Szia, köszi hogy jelezted. Javítottam az 1.0.8-as verzióban.

**Comment by vvarga01** [comment]
Szuper, hogy javítottad! Köszi! :)
